services:
    postgres:
        image: postgres:alpine
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
    postgres_test:
        image: postgres:alpine
        ports:
            - 5433:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
          - ./postgres-test-data:/var/lib/postgresql/data

  